### PR TITLE
update branch alias

### PR DESCRIPTION
**Pull request by cordoval**
we need to ride the wave to upgrade gush :) thanks

### CODE REVIEW

**Comment by webmozart** [comment]
Why? The master branch still *is* 1.0

**Comment by cordoval** [comment]
i discussed this with @sstok. Composer will prefer the stable tagged version when doing dev-master@dev I believe. Perhaps he can explain things further.

**Comment by webmozart** [comment]
This doesn't make sense to me... If you want the beta version, you should require 1.0@beta

**Comment by sstok** [comment]
I had some issues with (other packages) installing the last version (`@dev`) when there is a tag.
When you run composer update you would expect to get the last version.

`~1.0@dev` is the same as `>=1.0@dev,<2.0@dev` but for reasons Composer prefers the tagged version. So unless the branch-alias is higher you will not get the last version as 1.0-beta1 is preferred over 1.0-dev thus you can only use `dev-master@dev` to get the last version but will also run the risk of getting 2.0 at some point!

Using `1.0@beta` will not get 1.1 right? Correct if I'm wrong :)

This is the way its used most of the time, and it was the only way I could make this work.

**Comment by cordoval** [comment]
bump @webmozart should we close this?

**Comment by webmozart** [comment]
I'm travelling right now. I'll get back to you next week, need to understand this first :P

**Comment by cordoval** [comment]
closing as it has been picked for a slow death.

**Comment by Seldaek** [comment]
This doesn't seem to make sense to me. If you have `prefer-stable` set to true (it is false by default) then yes it would prefer a `1.0.0-beta` tag over `1.0.x-dev` branch, but otherwise `1.0.x-dev` is always bigger than any `1.0*` version as it is converted to `1.0.99-dev` internally.

**Comment by sstok** [comment]
Ah that must be the problem then :) I always use prefer-stable.
But is this also done when you use `@dev` flag? I would expect to get the dev even when prefer-stable it set as the version constraint is more explicit.

And what is the correct way to solve this?
Say the last tag is `1.0.4`, use `~1.0, >1.0.5` to always the latest?

**Comment by Seldaek** [comment]
`@dev` only allows dev versions but it doesn't require it so prefer-stable still overrides it, if you require `1.0.x-dev` then you demand that exact dev version so you'll get it. `@dev` isn't part of the constraint really.

**Comment by sstok** [comment]
Good know :+1: thank you very much for clarifying this :smile:

**Comment by cordoval** [comment]
:+1: thanks for clarification

**Pull request closed without merging**
